CREATE TABLE unit_of_measure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_unit_of_measure_name UNIQUE (name)
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uk_role_name UNIQUE (name)
);

CREATE TABLE school (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uk_school_name UNIQUE (name)
);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    school_id BIGINT NOT NULL,
    external_department_id BIGINT,
    CONSTRAINT fk_department_school
        FOREIGN KEY (school_id) REFERENCES school (id)
);

CREATE TABLE position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uk_position_name UNIQUE (name)
);

CREATE TABLE professor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    CONSTRAINT uk_professor_email UNIQUE (email),
    CONSTRAINT fk_professor_department
        FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE TABLE teacher_position (
    position_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    is_active BOOLEAN,
    CONSTRAINT pk_teacher_position PRIMARY KEY (position_id, teacher_id),
    CONSTRAINT fk_teacher_position_position
        FOREIGN KEY (position_id) REFERENCES position (id),
    CONSTRAINT fk_teacher_position_professor
        FOREIGN KEY (teacher_id) REFERENCES professor (id)
);

CREATE TABLE period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255),
    CONSTRAINT uk_period_name UNIQUE (name)
);

CREATE TABLE world (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uk_world_name UNIQUE (name)
);

CREATE TABLE strategic_bet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    world_id BIGINT NOT NULL,
    CONSTRAINT uk_strategic_bet_name UNIQUE (name),
    CONSTRAINT fk_strategic_bet_world
        FOREIGN KEY (world_id) REFERENCES world (id)
);

CREATE TABLE goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    reference_indicator VARCHAR(255),
    expected_value NUMERIC(12, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    world_id BIGINT,
    unit_of_measure_id BIGINT NOT NULL,
    CONSTRAINT fk_goal_world
        FOREIGN KEY (world_id) REFERENCES world (id),
    CONSTRAINT fk_goal_unit_of_measure
        FOREIGN KEY (unit_of_measure_id) REFERENCES unit_of_measure (id)
);

CREATE TABLE goal_period (
    goal_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    CONSTRAINT pk_goal_period PRIMARY KEY (goal_id, period_id),
    CONSTRAINT fk_goal_period_goal
        FOREIGN KEY (goal_id) REFERENCES goal (id),
    CONSTRAINT fk_goal_period_period
        FOREIGN KEY (period_id) REFERENCES period (id)
);

CREATE TABLE objective (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255),
    estimated_weight NUMERIC(5, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    created_by_external_user_id BIGINT,
    goal_id BIGINT NOT NULL,
    strategic_bet_id BIGINT NOT NULL,
    quarter SMALLINT NOT NULL DEFAULT 1,
    completion_percentage NUMERIC(10, 2),
    department_id BIGINT NOT NULL,
    academic_period_id BIGINT NOT NULL,
    CONSTRAINT fk_objective_created_by
        FOREIGN KEY (created_by) REFERENCES professor (id),
    CONSTRAINT fk_objective_goal
        FOREIGN KEY (goal_id) REFERENCES goal (id),
    CONSTRAINT fk_objective_strategic_bet
        FOREIGN KEY (strategic_bet_id) REFERENCES strategic_bet (id),
    CONSTRAINT fk_objective_department
        FOREIGN KEY (department_id) REFERENCES department (id),
    CONSTRAINT fk_objective_period
        FOREIGN KEY (academic_period_id) REFERENCES period (id),
    CONSTRAINT ck_objective_quarter
        CHECK (quarter BETWEEN 1 AND 4)
);

CREATE TABLE key_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    metric VARCHAR(255) NOT NULL,
    base_value NUMERIC(12, 2) NOT NULL,
    target_value NUMERIC(12, 2) NOT NULL,
    current_value NUMERIC(12, 2),
    progress_percentage NUMERIC(10, 2),
    created_at TIMESTAMP WITH TIME ZONE,
    academic_period_id BIGINT,
    unit_of_measure_id BIGINT NOT NULL,
    objective_id BIGINT NOT NULL,
    CONSTRAINT fk_key_result_period
        FOREIGN KEY (academic_period_id) REFERENCES period (id),
    CONSTRAINT fk_key_result_unit_of_measure
        FOREIGN KEY (unit_of_measure_id) REFERENCES unit_of_measure (id),
    CONSTRAINT fk_key_result_objective
        FOREIGN KEY (objective_id) REFERENCES objective (id)
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(255),
    status VARCHAR(255),
    actual_end_date DATE,
    jira_key VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    start_period VARCHAR(20) NOT NULL,
    end_period VARCHAR(20) NOT NULL,
    key_result_id BIGINT NOT NULL,
    contribution_weight NUMERIC(5, 2),
    link_status VARCHAR(255),
    external_project_id BIGINT,
    external_source VARCHAR(255),
    department_id BIGINT,
    department_name VARCHAR(255),
    start_date DATE,
    end_date DATE,
    global_progress NUMERIC(5, 2) NOT NULL DEFAULT 0,
    origin VARCHAR(255) NOT NULL DEFAULT 'LOCAL',
    sync_status VARCHAR(255) NOT NULL DEFAULT 'LOCAL_ONLY',
    last_synced_at TIMESTAMP WITH TIME ZONE,
    raw_external_payload TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_project_external_source_id UNIQUE (external_source, external_project_id),
    CONSTRAINT fk_project_key_result
        FOREIGN KEY (key_result_id) REFERENCES key_result (id),
    CONSTRAINT fk_project_department
        FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE TABLE project_teacher (
    project_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    joined_at DATE NOT NULL,
    left_at DATE,
    CONSTRAINT pk_project_teacher PRIMARY KEY (project_id, teacher_id, role_id),
    CONSTRAINT fk_project_teacher_project
        FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT fk_project_teacher_professor
        FOREIGN KEY (teacher_id) REFERENCES professor (id),
    CONSTRAINT fk_project_teacher_role
        FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE project_tutor (
    project_id BIGINT NOT NULL,
    tutor_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_project_tutor_project
        FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE TABLE project_progress_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    progress_percent NUMERIC(5, 2) NOT NULL,
    comment TEXT NOT NULL,
    milestones TEXT,
    created_by_external_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_project_progress_entry_project
        FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE TABLE project_key_result_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_result_id BIGINT NOT NULL,
    project_id BIGINT,
    external_project_id BIGINT,
    external_project_source VARCHAR(255) NOT NULL,
    contribution_weight NUMERIC(5, 2) NOT NULL,
    contribution_type VARCHAR(255) NOT NULL DEFAULT 'DIRECTA',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_project_key_result_link_key_result
        FOREIGN KEY (key_result_id) REFERENCES key_result (id),
    CONSTRAINT fk_project_key_result_link_project
        FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    actor_external_user_id BIGINT,
    actor_username VARCHAR(255),
    actor_roles TEXT,
    before_snapshot TEXT,
    after_snapshot TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_department_school ON department (school_id);
CREATE INDEX idx_professor_department ON professor (department_id);
CREATE INDEX idx_strategic_bet_world ON strategic_bet (world_id);
CREATE INDEX idx_goal_world ON goal (world_id);
CREATE INDEX idx_objective_goal ON objective (goal_id);
CREATE INDEX idx_objective_strategic_bet ON objective (strategic_bet_id);
CREATE INDEX idx_objective_period ON objective (academic_period_id);
CREATE INDEX idx_objective_department ON objective (department_id);
CREATE INDEX idx_key_result_objective ON key_result (objective_id);
CREATE INDEX idx_key_result_period ON key_result (academic_period_id);
CREATE INDEX idx_project_key_result ON project (key_result_id);
CREATE INDEX idx_project_periods ON project (start_period, end_period);
CREATE INDEX idx_project_status ON project (status);
CREATE INDEX idx_project_key_result_link_project ON project_key_result_link (project_id);
CREATE INDEX idx_project_key_result_link_key_result ON project_key_result_link (key_result_id);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_action ON audit_log (action);
