CREATE TABLE academic_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT uk_academic_period_name UNIQUE (name)
);

CREATE TABLE measurement_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_measurement_unit_name UNIQUE (name)
);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    external_department_id BIGINT
);

CREATE TABLE strategic_bet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_strategic_bet_name UNIQUE (name)
);

CREATE TABLE institutional_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    reference_indicator VARCHAR(255),
    expected_value NUMERIC(12, 2) NOT NULL,
    start_date DATE,
    end_date DATE,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    measurement_unit_id BIGINT NOT NULL,
    CONSTRAINT fk_institutional_goal_measurement_unit
        FOREIGN KEY (measurement_unit_id) REFERENCES measurement_unit (id)
);

CREATE TABLE goal_period (
    goal_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    CONSTRAINT uk_goal_period UNIQUE (goal_id, period_id),
    CONSTRAINT fk_goal_period_goal
        FOREIGN KEY (goal_id) REFERENCES institutional_goal (id),
    CONSTRAINT fk_goal_period_period
        FOREIGN KEY (period_id) REFERENCES academic_period (id)
);

CREATE TABLE objective (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_external_user_id BIGINT,
    department_id BIGINT NOT NULL,
    academic_period_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    strategic_bet_id BIGINT NOT NULL,
    CONSTRAINT fk_objective_department
        FOREIGN KEY (department_id) REFERENCES department (id),
    CONSTRAINT fk_objective_academic_period
        FOREIGN KEY (academic_period_id) REFERENCES academic_period (id),
    CONSTRAINT fk_objective_goal
        FOREIGN KEY (goal_id) REFERENCES institutional_goal (id),
    CONSTRAINT fk_objective_strategic_bet
        FOREIGN KEY (strategic_bet_id) REFERENCES strategic_bet (id)
);

CREATE TABLE key_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    metric VARCHAR(255) NOT NULL,
    base_value NUMERIC(12, 2) NOT NULL,
    target_value NUMERIC(12, 2) NOT NULL,
    current_value NUMERIC(12, 2),
    progress_percentage NUMERIC(8, 2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    measurement_unit_id BIGINT NOT NULL,
    objective_id BIGINT NOT NULL,
    CONSTRAINT fk_key_result_measurement_unit
        FOREIGN KEY (measurement_unit_id) REFERENCES measurement_unit (id),
    CONSTRAINT fk_key_result_objective
        FOREIGN KEY (objective_id) REFERENCES objective (id)
);

CREATE TABLE mte_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_project_id BIGINT,
    external_source VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    department_id BIGINT,
    department_name VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    start_period VARCHAR(255) NOT NULL,
    end_period VARCHAR(255),
    start_date DATE,
    end_date DATE,
    actual_end_date DATE,
    global_progress NUMERIC(5, 2) NOT NULL,
    origin VARCHAR(255) NOT NULL,
    sync_status VARCHAR(255) NOT NULL,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    raw_external_payload TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_project_external_source_id UNIQUE (external_source, external_project_id),
    CONSTRAINT fk_mte_project_department
        FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE TABLE mte_project_tutor (
    project_id BIGINT NOT NULL,
    tutor_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_mte_project_tutor_project
        FOREIGN KEY (project_id) REFERENCES mte_project (id)
);

CREATE TABLE project_progress_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    progress_percent NUMERIC(5, 2) NOT NULL,
    comment TEXT NOT NULL,
    milestones TEXT,
    created_by_external_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_project_progress_entry_project
        FOREIGN KEY (project_id) REFERENCES mte_project (id)
);

CREATE TABLE project_key_result_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_result_id BIGINT NOT NULL,
    project_id BIGINT,
    external_project_id BIGINT,
    external_project_source VARCHAR(255) NOT NULL,
    contribution_weight NUMERIC(5, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_project_key_result_link_key_result
        FOREIGN KEY (key_result_id) REFERENCES key_result (id),
    CONSTRAINT fk_project_key_result_link_project
        FOREIGN KEY (project_id) REFERENCES mte_project (id)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    actor_external_user_id BIGINT,
    actor_username VARCHAR(255),
    actor_roles TEXT,
    before_snapshot TEXT,
    after_snapshot TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_objective_period ON objective (academic_period_id);
CREATE INDEX idx_objective_department ON objective (department_id);
CREATE INDEX idx_key_result_objective ON key_result (objective_id);
CREATE INDEX idx_project_periods ON mte_project (start_period, end_period);
CREATE INDEX idx_project_status ON mte_project (status);
CREATE INDEX idx_project_key_result_link_project ON project_key_result_link (project_id);
CREATE INDEX idx_project_key_result_link_key_result ON project_key_result_link (key_result_id);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_action ON audit_log (action);
